#!/usr/bin/env bash
set -eu
set -o pipefail

nvr -c "let g:nvim_rs_id = jobstart(['cargo', 'run', '--', 'foo'], { 'rpc': v:true })"
echo ---
nvr --remote-expr "rpcrequest(g:nvim_rs_id, 'load', 'fd')"
echo ---
nvr --remote-expr "rpcrequest(g:nvim_rs_id, 'load', [1,2,'Three'])"
echo ---
nvr --remote-expr "rpcrequest(g:nvim_rs_id, 'ping')"
